
import { React, useState } from "react";
import axios from "axios";
const GetClassByClassID = () => {
    const [scheduleId, setId] = useState(0);
    const [classId, setClassId] = useState("");
    const [teacherId, setTeacherId] = useState("");
    const [subject, setSubject] = useState("");
    const [sessiontime, setSessionTime] = useState("");

    const Search = () => {
        axios
          .get("http://localhost:5225/api/ScheduleClass/GetClassByClassId/" + classId)
          .then((response) => {
            console.log(response.data);
            setId(response.data.scheduleId);
            setClassId(response.data.classId);
            setTeacherId(response.data.teacherId);
            setSubject(response.data.subject);
            setSessionTime(response.data.sessiontime);
          })
          .catch((error) => console.log(error));
      };

      return (
        <div className="container">
            <form>
                <table className="table">
                    <tbody>
                        <tr>
                            <td>Schedule Id</td>
                            <td>
                                <input
                                    type="text"
                                    value={scheduleId}
                                    placeholder="autogenerated"
                                    onChange={(e) => setId(e.target.value)}
                                />
                            </td>
                        </tr>
                        <tr>
                            <td>Class Id</td>
                            <td>
                                <input
                                    type="text"
                                    value={classId}
                                    onChange={(e) => setClassId(e.target.value)}
                                />
                            </td>
                        </tr>

                        <tr>
                            <td>Teacher Id</td>
                            <td>
                                <input
                                    type="text"
                                    value={teacherId}
                                    onChange={(e) => setTeacherId(e.target.value)}
                                />
                            </td>
                        </tr>

                        <tr>
                            <td>Subject</td>
                            <td>
                                <input
                                    type="text"
                                    value={subject}
                                    onChange={(e) => setSubject(e.target.value)}
                                />
                            </td>
                        </tr>

                        <tr>
                            <td>Sessiontime</td>
                            <td>
                                <input
                                    type="text"
                                    value={sessiontime}
                                    onChange={(e) => setSessionTime(e.target.value)}
                                />
                            </td>
                        </tr>
                       
                        <tr>
                            <td colSpan={2}>
                                
                                {/* <button type="submit" onClick={Search}>
                                    Search 
                                </button> */}
                             <button type="button" onClick={Search}>
                                Search
                            </button> 
                               
                            </td>
                        </tr>
                    </tbody>
                </table>
            </form>
        </div>
    );
};
export default GetClassByClassID;